# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: del_hub_availability.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'del_hub_availability.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x64\x65l_hub_availability.proto\x12\x10robot_to_commhub\"/\n\x19\x44\x65liveryHubAvailablityReq\x12\x12\n\ndel_hub_id\x18\x01 \x01(\t\",\n\x1a\x44\x65liveryHubAvailablityResp\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\x80\x01\n\x11\x44\x65liveryHubStatus\x12k\n\x0erobotToCommHub\x12+.robot_to_commhub.DeliveryHubAvailablityReq\x1a,.robot_to_commhub.DeliveryHubAvailablityRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'del_hub_availability_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DELIVERYHUBAVAILABLITYREQ']._serialized_start=48
  _globals['_DELIVERYHUBAVAILABLITYREQ']._serialized_end=95
  _globals['_DELIVERYHUBAVAILABLITYRESP']._serialized_start=97
  _globals['_DELIVERYHUBAVAILABLITYRESP']._serialized_end=141
  _globals['_DELIVERYHUBSTATUS']._serialized_start=144
  _globals['_DELIVERYHUBSTATUS']._serialized_end=272
# @@protoc_insertion_point(module_scope)
