# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import del_hub_pack_accept_pb2 as del__hub__pack__accept__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in del_hub_pack_accept_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PackageStatusStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.robotToServer = channel.unary_unary(
                '/robot_to_commhub.PackageStatus/robotToServer',
                request_serializer=del__hub__pack__accept__pb2.PackageAcceptanceReq.SerializeToString,
                response_deserializer=del__hub__pack__accept__pb2.PackageAcceptanceResp.FromString,
                _registered_method=True)


class PackageStatusServicer(object):
    """Missing associated documentation comment in .proto file."""

    def robotToServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PackageStatusServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'robotToServer': grpc.unary_unary_rpc_method_handler(
                    servicer.robotToServer,
                    request_deserializer=del__hub__pack__accept__pb2.PackageAcceptanceReq.FromString,
                    response_serializer=del__hub__pack__accept__pb2.PackageAcceptanceResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot_to_commhub.PackageStatus', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot_to_commhub.PackageStatus', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PackageStatus(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def robotToServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_to_commhub.PackageStatus/robotToServer',
            del__hub__pack__accept__pb2.PackageAcceptanceReq.SerializeToString,
            del__hub__pack__accept__pb2.PackageAcceptanceResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
