# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: del_hub_pack_accept.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'del_hub_pack_accept.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x64\x65l_hub_pack_accept.proto\x12\x10robot_to_commhub\"<\n\x14PackageAcceptanceReq\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x12\n\ndel_hub_id\x18\x02 \x01(\t\")\n\x15PackageAcceptanceResp\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x32q\n\rPackageStatus\x12`\n\rrobotToServer\x12&.robot_to_commhub.PackageAcceptanceReq\x1a\'.robot_to_commhub.PackageAcceptanceRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'del_hub_pack_accept_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PACKAGEACCEPTANCEREQ']._serialized_start=47
  _globals['_PACKAGEACCEPTANCEREQ']._serialized_end=107
  _globals['_PACKAGEACCEPTANCERESP']._serialized_start=109
  _globals['_PACKAGEACCEPTANCERESP']._serialized_end=150
  _globals['_PACKAGESTATUS']._serialized_start=152
  _globals['_PACKAGESTATUS']._serialized_end=265
# @@protoc_insertion_point(module_scope)
